### Home page
GET http://localhost:3001

### GET how many contacts the phonebook has
GET http://localhost:3001/info

### GET all notes
GET http://localhost:3001/api/persons

### GET one persons for id
GET http://localhost:3001/api/persons/664f52ff4c86f544cb82eeb9

### Error test GET one person for id
GET http://localhost:3001/api/persons/9999

### Create a new persons on the phonebook
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "person test",
  "number": "123-456-789"
}

### Error test Create a new persons on the phonebook
POST http://localhost:3001/api/persons
Content-Type: text/plain

{
  "name": "person test",
  "number": "123-456-789"
}

### Error test Create a new persons with the same name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "123-456-789"
}

### DELETE a person for id
DELETE http://localhost:3001/api/persons/2

### Error test DELETE a person for id
DELETE http://localhost:3001/api/persons/999